export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCESS";
export const SET_TOKEN_INFO = "SET_TOKEN_INFO";
export const GET_APP_THEME = "GET_APP_THEME";
export const SET_APP_THEME = "SET_APP_THEME";
