import { mapSlotParameterValidationDef } from "./ValidationDef";
import { getSlotParameters } from "./Utilities";

export const emptyCarrier = {
    Code: "",
    Name: "",
    Address: null,
    ContactPerson: null,
    Phone: "",
    Email: null,
    Mobile: null,
    ShareholderCode: "",
    ShareholderCodes: [],
    PermitNumber: null,
    PermitExpiryDate: null,
    Description: null,
    EnforceSequence: false,
    AllowOnlyWeighIn: false,
    MarkedForDeletion: false,
    Status: true,
    Remarks: null,
    LastActiveDate: new Date(),
    CreatedDate: new Date(),
    LastUpdatedDate: new Date(),
    LastUpdatedBy: null,
    AssociatedDriversCount: "0",
    AssociatedVehiclesCount: "0",
    TransportationType: "",
    IdentityNumber: "00000000U",
    Attributes: [],
    TerminalCodes: [],
};

export const emptyDriver = {
  Name: "",
  Code: "",
  ShareholderCode: "",
  CarrierCode: "",
  MailID: null,
  Mobile: null,
  NRIC: null,
  Phone: null,
  Remarks: "",
  LanguageCode: "",
  LanguageName: "",
  License1: null,
  License1ExpiryDate: null,
  License1IssueDate: null,
  License2: null,
  License2ExpiryDate: null,
  License2IssueDate: null,
  License3: null,
  License3ExpiryDate: null,
  License3IssueDate: null,
  IsHazardousAllowed: false,
  HazardousLicenseExpiry: null,
  Active: true,
  DateOfBirth: null,
  DriverImage: [],
  MarkedForDeletion: false,
  CreatedDate: null,
  LastUpdatedDate: null,
  LastUpdatedBy: null,
  Attributes: [],
  TerminalCodes: [],
};

export const emptyCustomer = {
    Code: "",
    Name: "",
    LanguageCode: "",
    LanguageName: "",
    Address: null,
    ContactPerson: null,
    Phone: "",
    Email: null,
    Mobile: null,
    ShareholderCode: "",
    Description: null,
    MarkedForDeletion: false,
    Status: true,
    Remarks: null,
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    LastUpdatedBy: null,
    TransportationTypes: [],
    TerminalCodes: [],
    Attributes: [],
};

export const emptyTrailer = {
  Active: true,
  Attributes: [],
  CarrierCompanyCode: null,
  Code: "",
  Compartments: [],
  CreatedTime: null,
  Description: "",
  FinishedProductCode: null,
  Height: null,
  LWHUOM: null,
  Length: null,
  LicenseExpiryData: null,
  LoadingType: "TOP_AND_BOTTOM",
  LastActiveTime: null,
  LastUpdateTime: null,
  MaxLoadableVolume: "",
  MaxLoadableWeight: "",
  MaxLoadableWeight_UI: "",
  MinLoadableVolume: null,
  MinLoadableWeight: null,
  Name: "",
  NoOfSeals: null,
  ProductType: "ALLPROD",
  RailWagonCategory: null,
  Remarks: "",
  RestrictedProductCode: null,
  ShareholderCode: null,
  TareTolMaxAbs: null,
  TareTolMinAbs: null,
  TareWeight: "",
  TerminalCodes: [],
  ToleranceUOM: null,
  TrailerType: null,
  TransportationType: "Road",
  VolumeUOM: null,
  WeightUOM: "kg",
  Width: null,
  HazardousLicenseExpiry: null,
  HazardousCategory: null
};

export const emptyOrigin = {
    Code: "",
    Name: "",
    Address: null,
    Status: true,
    Attributes: [],
    Remarks: null,
    LastActiveDate: new Date(),
    CreatedDate: new Date(),
    LastUpdatedDate: new Date(),
    LastUpdatedBy: null,
    ShareholderCode: "",
    TerminalCodes: [],
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    TransportationTypes: [],
    AssociatedSuppliers: [],
};

export const emptyDestination = {
    Code: "",
    Name: "",
    Description: null,
    Attributes: [],
    DestinationType: "DEFAULT_DESTINATION_TYPE",
    Address: null,
    ContactPerson: null,
    MobileNumber: null,
    PhoneNumber: null,
    Email: null,
    MarkedForDeletion: false,
    Status: true,
    Remarks: null,
    LastUpdatedBy: "",
    Customer: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    ShareholderCode: "",
    TransportationTypes: [],
    City: null,
    State: null,
    Country: null,
    ZipCode: null,
    ListCustomerDestinationInfo: [],
    TerminalCodes: [],
};

export const emptyPrimeMover = {
    Active: true,
    Attributes: [],
    Description: "",
    CarrierCompanyCode: "",
    Code: "",
    Height: null,
    LWHUOM: null,
    Length: null,
    LicensceNo: null,
    MaxLoadableWeight: null,
    MaxAllowableWeightUOM: null,
    Name: "",
    PrimeMoverType: "NON_RIGID_PRIMEMOVER",
    Remarks: "",
    RoadTaxNo: null,
    RoadTaxNoExpiryDate: null,
    RoadTaxNoIssueDate: null,
    TareWeight: "",
    TareWeightUOM: "kg",
    TerminalCodes: [],
    Width: null,
    licenseExpiryDate: null,
    LastUpdatedTime: null,
    LastActiveTime: null,
    CreatedTime: null,
};

export const emptyRigidTruck = {
    Active: true,
    Attributes: [],
    CarrierCompanyCode: null,
    Code: "",
    Description: "",
    Height: null,
    LWHUOM: null,
    Length: null,
    LicenseNo: "",
    LicenseNoExpiryDate: null,
    LicenseNoIssueDate: null,
    MaxLoadableWeight: "",
    MaxLoadableVolume: "",
    Name: "",
    ProductType: "ALLPROD",
    RegisteredInCountry: "",
    Remarks: "",
    RoadTaxNo: null,
    RoadTaxNoExpiryDate: null,
    RoadTaxNoIssueDate: null,
    ShareholderCode: "",
    ShareholderCodes: "",
    TareTolMaxAbs: "",
    TareTolMinAbs: "",
    TareWeight: "",
    TerminalCodes: [],
    ToleranceUOM: null,
    TransportationType: "Road",
    VehicleGroupType: null,
    VehiclePrimeMovers: [],
    IsBonded: false,
    VehicleCustomsBondNo: null,
    BondExpiryDate: null,
    VehicleTrailers: [{
        Attributes: [],
        CarrierCompanyCode: "",
        ShareholderCode: "",
        TrailerCode: "",
        TrailerSeq: "",
        VehicleCode: "",
        Trailer: {
            Active: false,
            Attributes: [],
            CarrierCompanyCode: "",
            Code: "",
            Compartments: [],
            CreatedTime: null,
            Description: "",
            FinishedProductCode: null,
            Height: null,
            LWHUOM: null,
            Length: null,
            LicenseExpiryDate: "",
            LoadingType: "TOP_AND_BOTTOM",
            LastActiveTime: null,
            LastUpdateTime: null,
            MaxLoadableVolume: "",
            MaxLoadableWeight: "",
            MinLoadableVolume: null,
            MinLoadableWeight: null,
            Name: "",
            NoofSeals: null,
            ProductType: "",
            RailWagonCategory: null,
            Remarks: "",
            RestrictedProductCode: null,
            ShareholderCode: "",
            TareTolMaxAbs: null,
            TareTolMinAbs: null,
            TareWeight: "",
            TerminalCodes: null,
            ToleranceUOM: null,
            TransportationType: "Road",
            TrailerType: "RIGID_TRAILER",
            VolumeUOM: null,
            WeightUOM: null,
            Width: null,
        },
    }, ],
    VehicleType: "RIGID_TRUCK",
    VolumeUOM: null,
    WeightUOM: "kg",
    Width: null,
    Owner: null,
};

export const emptyVehicle = {
  Active: true,
  Attributes: [],
  CarrierCompanyCode: null,
  Code: "",
  Description: "",
  Height: null,
  LWHUOM: null,
  Length: null,
  LicenseNo: "",
  LicenseNoExpiryDate: null,
  LicenseNoIssueDate: null,
  MaxLoadableWeight: "",
  MaxLoadableVolume: "",
  Name: "",
  ProductType: "ALLPROD",
  RegisteredInCountry: "",
  Remarks: "",
  RoadTaxNo: null,
  RoadTaxNoExpiryDate: null,
  RoadTaxNoIssueDate: null,
  ShareholderCode: "",
  ShareholderCodes: "",
  TareTolMaxAbs: "",
  TareTolMinAbs: "",
  TareWeight: "",
  TerminalCodes: [],
  ToleranceUOM: null,
  TransportationType: "Road",
  VehicleGroupType: null,
  VehiclePrimeMovers: [],
  VehicleTrailers: [],
  VehicleType: null,
  VolumeUOM: null,
  WeightUOM: null,
  Width: null,
  Owner: null,
  IsBonded: false,
  VehicleCustomsBondNo: null,
  BondExpiryDate: null,
  HazardousLicenseExpiry: null,
  HazardousCategory: null
};

export const emptyFinishedProduct = {
  Active: true,
  AliasName: "",
  Attributes: [],
  Code: "",
  Color: "",
  CreatedTime: "",
  Density: "",
  DensityUOM: null,
  Description: "",
  ExportGrade: false,
  FinishedProductItems: [],
  LastActiveTime: new Date(),
  LastUpdatedBy: "",
  LastUpdatedTime: new Date(),
  LatestVersion: "",
  Name: "",
  ProductFamilyCode: null,
  ProductIndex: "",
  ProductType: "ALLPROD",
  Remarks: "",
  Shareholdercode: "",
  TerminalCodes: "",
  ToleranceQuantity: "",
  ToleranceQuantityForMarine: "",
  ToleranceQuantityForPipeline: "",
  ToleranceQuantityForRail: "",
  ToleranceQuantityUOM: null,
  WeighBridgeWeighingRequired: false,
  WeighingRequired: false,
  HazardousCategory: null,
  SFLPercent: 100,
  HazardousNumber: null,
};

export const emptyShipment = {
    ShipmentCode: "",
    SequenceNo: 0,
    VehicleCode: null,
    ShipmentType: 0,
    ShipmentSource: 3,
    ShipmentStatus: 8,
    Status: "READY",
    ScheduledDate: new Date(),
    ShipmentQuantityUOM: "L",
    UserCode: null,
    ShareholderCode: "",
    DriverCode: null,
    IsPriority: false,
    PlannedTripNo: null,
    ActualTripNo: null,
    EntryTime: null,
    ExitTime: null,
    LoadStartTime: null,
    LoadEndTime: null,
    SealStartTime: null,
    SealEndTime: null,
    Active: true,
    ForceClosed: false,
    LastActiveTime: new Date(),
    Remarks: null,
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    CarrierCode: null,
    Description: null,
    ForceClosureReason: null,
    LastUpdatedBy: null,
    IsVolumeBased: false,
    BolPrCount: 0,
    ManualAction: 0,
    fanPrCount: 0,
    IsBonded: false,
    ShipmentBondNo: null,
    ShipmentDestinationCompartmentsInfo: [],
    ShipmentCompartments: [],
    ShipmentTrailerInfo: [],
    ShipmentDetailsInfo: [],
    Attributes: [],
    CreatedFromEntity: 0,
    OrderCodes: null,
    ContractCodes: null,
    ShipmentStatusExtended: false,
    Loadid: null,
    LoadIDItemNumber: null,
    HSEInspectionStatus: null,
    BOLPrintCount: 0,
    FANPrintCount: 0,
    //DCH
    AuthorizationNumbers: null,
    DCHDriverInputs: null,
    TransloadSourceType: null,

    TerminalCodes: [],

    ActualTerminalCode: null,
    AvoidOrderContractSync: false,
};

export const emptyOrder = {
    Active: true,
    Attributes: [],
    CustomerCode: "",
    DeliveryDate: null,
    Description: "",
    OrderCode: "",
    OrderDate: null,
    OrderEndDate: null,
    OrderStartDate: null,
    OrderItems: [],
    OrderStatus: null,
    OrderType: 0,
    Remarks: "",
    ShareholderCode: null,
    TerminalCodes: [],
    OrderSource: 1
};

export const emptyContract = {
    Active: true,
    Attributes: [],
    CarrierCollection: [],
    ContractCode: "",
    ContractItems: [],
    ContractSource: 1,
    ContractType: 0,
    CustomerCode: "",
    Description: null,
    EndDate: null,
    Remarks: null,
    ShareholderCode: "",
    StartDate: null,
    Status: null,
    TerminalCodes: [],
    TransportationType: null,
};

export const emptyReceipt = {
    Active: true,
    ReceiptCode: "",
    CarrierCode: "",
    Description: null,
    DriverCode: "",
    Remarks: null,
    ScheduledDate: new Date(),
    ShareholderCode: "",
    ReceiptStatus: "READY",
    ReceiptType: 0, //"COMPARTMENT",
    VehicleCode: null,
    ReceiptQuantityUOM: "", //"L",
    LastUpdatedBy: "",
    CreatedFromEntity: 0,
    TransportationType: "ROAD",
    ReceiptSource: "TM_UI", //2,
    TerminalCodes: [],
    ReceiptOriginTerminalCompartmentsInfo: [],
    CustomerInventoryPlanList: [],
    CreatedTime: new Date(),
    LastActiveTime: new Date(),
    LastUpdatedTime: new Date(),
    ReceiptCompartmentsInfo: [],
    ReceiptTrailersInfo: [],
    SupplierCode: "",
    Attributes: [],
    IsBonded: false
};

export const emptyMarineDispatch = {
    DispatchSource: "TM_UI",
    EntryTime: null,
    ExitTime: null,
    LoadStartTime: null,
    LoadEndTime: null,
    SealStartTime: null,
    SealEndTime: null,
    BOLPrintCount: 0,
    FANPrintCount: 0,
    ManualAction: 0,
    ForceClosed: false,
    ForceClosureReason: null,
    LastActiveTime: null,
    CreatedTime: new Date(),
    UpdatedBy: null,
    UpdatedTime: new Date(),
    ActualTerminalCode: null,
    DispatchCode: "",
    Description: "",
    ScheduledDate: new Date(),
    RouteCode: "",
    DispatchType: 0,
    VesselCode: "",
    CarrierCode: "",
    CreatedFromEntity: 0,
    DispatchStatus: "READY",
    GeneralTMUser: null,
    IsBonded: false,
    BondNumber: null,
    TransportationType: "MARINE",
    QuantityUOM: "L",
    Active: true,
    Remarks: "",
    DispatchItemPlanList: [],
    DispatchCompartmentDetailPlanList: [],
    Attributes: [],
    TerminalCodes: [],
    DispatchCompartmentPlanList: [],
};

export const emptyMarineReceipt = {
    ReceiptSource: "TM_UI",
    EntryTime: null,
    ExitTime: null,
    UnloadStartTime: null,
    UnloadEndTime: null,
    SealStartTime: null,
    SealEndTime: null,
    BODPrintCount: 0,
    RANPrintCount: 0,
    ForceClosed: false,
    ForceClosureReason: null,
    LastActiveTime: null,
    CreatedTime: new Date(),
    UpdatedBy: null,
    LastUpdatedTime: new Date(),
    UpdatedTime: new Date(),
    ActualTerminalCode: null,
    ReceiptCode: "",
    Description: "",
    ScheduledDate: new Date(),
    ReceiptType: 0,
    CreatedFromEntity: 0,
    ReceiptStatus: "READY",
    VesselCode: "",
    CarrierCode: "",
    Active: true,
    Remarks: "",
    IsBonded: false,
    BondNumber: null,
    QuantityUOM: "L",
    TransportationType: "MARINE",
    RailMarineReceiptCompartmentDetailPlanList: [],
    Attributes: [],
    TerminalCodes: [],
    RailMarineReceiptCompartmentPlanList: [],
};

export const emptySupplier = {
    Code: "",
    Name: "",
    Description: null,
    Attributes: [],
    Address: null,
    ContactPerson: null,
    Mobile: null,
    Phone: null,
    Email: null,
    MarkedForDeletion: false,
    Status: true,
    Remarks: null,
    LastUpdatedBy: "",
    OriginTerminal: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    ShareholderCode: "",
    TransportationTypes: [],
    SupplierOriginTerminals: [],
    TerminalCodes: [],
};
export const emptyMarineTransloading = {
    ReceiptCode: "",
    NoofComps: 0,
    NoOfProducts: 0,
    receiptPlannedQty: 0,
    totalPlannedQtyForTransloadingWagons: 0,
    totalUnloadedQtyForTransloadingWagons: 0,
    totalNoOfTransWagons: 0,
    PlanQuantityUOM: "",
    UnloadedQuantityUOM: "",
    TransportationType: "",
    selectCompartment: {
        CompartmentCode: "",
        CompartmentProduct: "",
        ReceiptCompartmentStatus: "",
        PlannedQuantity: 0,
        PlanQuantityUOM: "",
        UnloadedQuantity: 0,
        UnloadedQuantityUOM: "",
    },
    showShipment: false,
    showLoadingDetails: false,
    lstCompartmentBPs: [],
    lstCompartmentList: [],
    TerminalCodes: [],
};

export const emptyRailDispatch = {
    DispatchSource: "TM_UI",
    EntryTime: null,
    ExitTime: null,
    LoadStartTime: null,
    LoadEndTime: null,
    SealStartTime: null,
    SealEndTime: null,
    BOLPrintCount: 0,
    FANPrintCount: 0,
    ManualAction: 0,
    ForceClosed: false,
    ForceClosureReason: null,
    LastActiveTime: null,
    CreatedTime: new Date(),
    UpdatedBy: "",
    UpdatedTime: new Date(),
    ActualTerminalCode: null,
    DispatchCode: "",
    Description: "",
    ScheduledDate: new Date(),
    RouteCode: null,
    DispatchType: 2,
    VesselCode: null,
    CarrierCode: null,
    CreatedFromEntity: 0,
    DispatchStatus: "READY",
    GeneralTMUser: null,
    IsBonded: false,
    BondNumber: null,
    TransportationType: null,
    QuantityUOM: "kg",
    Active: true,
    Remarks: "",
    DispatchItemPlanList: [],
    DispatchCompartmentDetailPlanList: null,
    Attributes: [],
    TerminalCodes: [],
    DispatchCompartmentPlanList: null,
};

export const emptyRailReceipt = {
    Active: true,
    ActualTerminalCode: null,
    Attributes: [],
    BODPrintCount: 0,
    BondNumber: null,
    CarrierCode: null,
    CreatedFromEntity: 0,
    CreatedTime: new Date(),
    Description: "",
    EntryTime: new Date(),
    ExitTime: new Date(),
    ForceClosed: false,
    ForceClosureReason: null,
    IsBonded: false,
    LastActiveTime: new Date(),
    LastUpdatedTime: new Date(),
    QuantityUOM: "kg",
    RANPrintCount: 0,
    RailMarineReceiptCompartmentDetailPlanList: [],
    RailMarineReceiptCompartmentPlanList: [],
    ReceiptCode: "",
    ReceiptSource: "TM_UI",
    ReceiptStatus: "READY",
    ReceiptType: 0,
    Remarks: "",
    ScheduledDate: new Date(),
    SealEndTime: new Date(),
    SealStartTime: new Date(),
    TerminalCodes: [],
    TransportationType: null,
    UnloadEndTime: new Date(),
    UnloadStartTime: new Date(),
    UpdatedBy: "",
    UpdatedTime: new Date(),
    VesselCode: null,
};

export const emptyRailRoute = {
    RouteCode: "",
    RouteName: null,
    Description: "",
    DestinationCode: "",
    DepartureTime: new Date(),
    IntermediateDestinationList: [],
    Active: true,
    Remarks: "",
    LastActiveTime: null,
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    TerminalCodes: [],
};

export const emptyRailWagon = {
    Abandoned: false,
    Active: true,
    Attributes: [],
    CarrierCompanyCode: "",
    Code: "",
    Compartments: [],
    CreatedTime: new Date(),
    Crippled: false,
    DateField1Flag: null,
    DateField2: null,
    DateField2Flag: null,
    Description: "",
    FinishedProductCode: null,
    Height: null,
    InUse: false,
    LWHUOM: null,
    LastActiveTime: null,
    LastUpdateTime: new Date(),
    LastUpdatedBy: "",
    Length: null,
    LicenseExpiryDate: null,
    LoadingType: "",
    LogicMasterCode: null,
    MaxLoadableVolume: null,
    MaxLoadableWeight: null,
    MinLoadableVolume: null,
    MinLoadableWeight: null,
    Name: "",
    NoOfSeals: null,
    ProductType: "",
    RailWagonCategory: "",
    Remarks: "",
    RemarksForCripple: "",
    RestrictedProductCode: null,
    ShareholderCode: null,
    TareTolMaxAbs: null,
    TareTolMinAbs: null,
    TareWeight: null,
    TerminalCodes: null,
    ToleranceUOM: null,
    TrailerType: "",
    TransportationType: "",
    VolumeUOM: "",
    WeightUOM: "",
    Width: null,
};

export const emptyPipelineDispatch = {
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    CreatedTime: new Date(),
    Remarks: "",
    ForceClosureReason: null,
    ForceClosed: false,
    BOLPrintCount: null,
    BondNumber: null,
    IsBonded: false,
    DispatchEndTime: new Date(),
    DispatchStartTime: new Date(),
    ManualAction: null,
    IsPriority: false,
    Source: null,
    QuantityUOM: null,
    Quantity: null,
    PipelineDispatchStatus: "READY",
    ScheduledEndTime: new Date(),
    ScheduledStartTime: new Date(),
    PipelineHeaderMeterCode: null,
    PipelineHeaderCode: null,
    FinishedProductCode: null,
    DestinationCode: null,
    CustomerCode: null,
    TransactionMode: null,
    ShareholderCode: null,
    PipelineDispatchCode: "",
    Attributes: [],
    PipelineDispatchTanks: [],
    TerminalCodes: [],
    ActualTerminalCode: "",
};

export const emptyPipelineReceipt = {
    PipelineReceiptCode: "",
    Source: "",
    ActualTerminalCode: "",
    ShareholderCode: "",
    TransactionMode: "",
    OriginTerminalCode: "",
    FinishedProductCode: "",
    SupplierCode: "",
    PipelineHeaderCode: "",
    PipelineHeaderMeterCode: null,
    ScheduledStartTime: new Date(),
    ScheduledEndTime: new Date(),
    PipelineReceiptStatus: "READY",
    Quantity: null,
    QuantityUOM: null,
    TerminalCodes: [],
    PipelineReceiptTanks: [],
    ReceiptStartTime: new Date(),
    ReceiptEndTime: new Date(),
    Remarks: "",
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    Attributes: []
};

export const emptySMSConfiguration = {
    LastUpdatedTime: new Date(),
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    Remarks: "",
    Active: true,
    SMSMessageCode: "",
    RecipientList: "",
    MessageText: "",
    EmailSMSEntityType: "",
    SelectedParamField: "",
    EntityParamType: "",
};
export const emptyEmailConfiguration = {
    Active: true,
    Attachment: false,
    EmailMessageCode: "",
    EmailSMSEntityType: "",
    RecipientListBCC: "",
    RecipientListCC: "",
    RecipientListTo: "",
    Remarks: "",
    Subject: "",
    LastActiveTime: new Date(),
    LastUpdatedTime: new Date(),
    CreatedTime: new Date(),
    MessageText: "",
    Priority: null,
    Recipients: [],
};

export const emptyHSEConfiguration = {
  Description: "",
  IsDateTimeDisplayRequired: false,
  IsRemarksDisplayRequired: false,
  LastUpdatedBy: null,
  LastUpdatedTime: new Date(),
  LocationTypeCode: null,
  Questions: null,
  TransactionType: null,
  TransportationType: null,
  TransportationUnit: null,
  TransportationUnitType: null,
  TerminalCode: null,
};

export const emptyShareholder = {
    ShareholderCode: "",
    ShareholderName: "",
    Description: "",
    Active: true,
    Remarks: "",
    LastUpdatedBy: "",
    ExternalSystemCode: "1",
    IsBypass: false,
    SealCode: "",
    LastActiveDate: new Date(),
    CreatedDate: new Date(),
    LastUpdatedDate: new Date(),
    TerminalCodes: [],
    Attributes: [],
};

export const emptyNonFillingVehicle = {
    Active: true,
    Attributes: [],
    CarrierCompanyCode: null,
    Code: "",
    Description: "",
    Height: null,
    LWHUOM: null,
    Length: null,
    LicenseNo: null,
    LicenseNoExpiryDate: null,
    LicenseNoIssueDate: null,
    MaxLoadableWeight: "",
    MaxLoadableVolume: "",
    Name: "",
    ProductType: null,
    RegisteredInCountry: null,
    Remarks: "",
    RoadTaxNo: null,
    RoadTaxNoExpiryDate: null,
    RoadTaxNoIssueDate: null,
    ShareholderCode: "",
    ShareholderCodes: null,
    TareTolMaxAbs: null,
    TareTolMinAbs: null,
    TareWeight: null,
    TerminalCodes: [],
    ToleranceUOM: null,
    TransportationType: "ROAD",
    VehicleGroupType: null,
    VehiclePrimeMovers: [],
    VehicleTrailers: [],
    VehicleType: "NON_FILLING_VEHICLE",
    VolumeUOM: null,
    WeightUOM: null,
    Width: null,
    Owner: null,
};

export const emptyLocation = {
    LocationCode: "",
    LocationName: "",
    LocationType: "",
    Description: "",
    AssociatedLocationCode: "",
    AssociatedLocationType: "",
    Active: true,
    Attributes: [],
    Remarks: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    LastUpdatedBy: "",
    AssociatedDevices: [],
    AssociatedLocationsList: [],
};

export const emptyGantry = {
    Code: "",
    Name: "",
    ParentCode: "",
    Active: true,
    EntityRemarks: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
};

export const emptyDevice = {
    Code: "",
    Name: "",
    Active: true,
    Remarks: "",
    DeviceType: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    AdditiveUOM: "",
    DensityUOM: "",
    Description: "",
    LastUpdatedBy: "",
    Attributes: [],
    AssociatedChannels: [],
    ESDTagName: "",
    IsDualBay: true,
    IsTransloading: true,
    MassUOM: "",
    Model: "",
    MultiDrop: true,
    NoOfAdditive: 0,
    NoOfArms: 0,
    NodeAddress: "",
    PointName: "",
    PressureUOM: "",
    Prover: true,
    ReceiptSource: null,
    TemperatureUOM: "",
    TerminalCode: "",
};
export const emptyBaseProduct = {
    Active: true,
    AliasName: "",
    Code: "",
    Color: "",
    CreatedTime: "",
    Density: "",
    DensityUOM: null,
    Description: "",
    MinDensity: "",
    MaxDensity: "",
    ExportGrade: false,
    LastActiveTime: new Date(),
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    Name: "",
    ProductType: "ALLPROD",
    Remarks: "",
    TerminalCodes: [],
    IsAdditive: false,
    VapourRecoveryProduct: false,
    HazchemCode: "",
    Attributes: [],
};

export const emptyChannel = {
    ChannelCode: "",
    ChannelType: "",
    PrimaryAddress: "",
    SecondaryAddress: "",
    PrimaryPort: "",
    SecondaryPort: "",
    IsEthernet: false,
    SendTimeOut: "5000",
    ReceiveTimeOut: "5000",
    RetryInterval: "10000",
    ConnectionRetries: "5",
    IsMultiDrop: false,
    IsPrevMultiDrop: "",
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    DataBits: null,
    StopBits: null,
    ParityBits: null,
    BaudRate: null,
    PortType: 0,
    PrevChnId: "",
    PrevChannelId: ""
};
export const emptyMapTransactions = {
    BatchDetailsList: [],
    QuantityUOM: "",
    FinishedProductCode: "",
    ActualQuantity: null,
    BcuCode: "",
    BatchID: null,
    TransactionID: null,
    TransactionType: "DISPATCH",
    TransportationType: "",
    TransactionCode: "",
    CompartmentCode: "",
    CompartmentSeqNoInVehicle: "",
    WagonCode: "",
    EntityCode: "",
    TransLoadSource: null,
    TransLoadBcu: false,
    ShareholderCode: "",
    LoadingDetails: [],
    RailMarineTransactions: [],
};

export const emptyLoadingArm = {
    Code: "",
    Name: "",
    ArmNumberInBCU: "",
    Attributes: [],
    BlendType: "",
    ArmLoadingType: "",
    NodeAddress: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    CleanLineFinishQuantity: "0",
    CleanLineFinishQuantityUOM: "L",
    MinimumLoadableQuantity: "0",
    MLQtyUOM: "L",
    MainlineMeters: "",
    AdditiveMeters: "",
    Remarks: "",
    Description: "",
    Status: true,
    DeniedFPs: [],
    PossibleFPS: [],
    Swingable: false,
};
export const emptyIsland = {
    Code: "",
    Name: "",
    ParentCode: "",
    Active: true,
    EntityRemarks: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
};

export const emptyBay = {
    Active: true,
    Attributes: [],
    BayAllocationMode: true,
    BayCode: "",
    BayPriority: "",
    BayType: "BOTH",
    IslandCode: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    CurrentQueue: "",
    Description: "",
    EnabledForBayAllocation: false,
    IsVolumeBased: false,
    LoadingType: "BOTTOM",
    MaximumQueue: "",
    Name: "",
    Remarks: "",
    Segment: null,
    SupportedProducts: [],
    TotalLoadedVehicles: 0,
    VehicleSpecificType: "",
};

export const emptyHSEInspection = {
    DispatchReceiptCode: null,
    HSEInspectionStatus: null,
    ID: null,
    InspectedItems: null,
    LastInspectedBy: null,
    LastInspectedTime: null,
    LocationCode: null,
    OverAllHSEInspectionStatus: null,
    MasterInpsectionResultsRefId: null,
    Remarks: "",
    ShareholderCode: null,
    ShipmentCode: null,
    TransactionType: null,
    TransportationType: null,
    TransportationUnit: null,
    TransportationUnitType: null,
    TransportationUnitTypeCode: null,
    VehicleCode: null,
    HSEDocumentsInfo: [],
    Attributes: [],
};

export const emptyLeakageManualEntry = {
    TankCode: "",
    NetQuantity: "",
    DensityUOM: "",
    Density: "",
    NetEndTotalizer: "",
    NetStartTotalizer: "",
    GrossEndTotalizer: "",
    GrossStartTotalizer: "",
    StartTime: new Date(),
    EndTime: new Date(),
    UpdatedTime: null,
    ProductCategory: "",
    ProductCode: "",
    Attributes: [],
    LeakageQtyUom: "",
    LeakageQty: "",
    MeterCode: "",
};

export const emptyAccountedTransaction = {
    CreatedDate: new Date(),
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    Comments: "",
    CustomerCode: "",
    TankCode: "",
    TransactionStartTime: new Date(),
    TransactionEndTime: new Date(),
    DensityUOM: "",
    Density: "",
    QuantityUOM: "",
    UnAccountedNetQuantity: "",
    UnAccountedGrossQuantity: "",
    BaseProductCode: "",
    TransportationType: "",
    ShareholderCode: "",
    ReconciliationCode: "",
    UnAccountedTransactionTypeCode: "",
    Attributes: [],
};
export const emptyAccountedMeterTransaction = {
    MeterCode: "",
    CreatedDate: new Date(),
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    Comments: "",
    TankCode: "",
    TransactionStartTime: new Date(),
    TransactionEndTime: new Date(),
    DensityUOM: "",
    Density: "",
    QuantityUOM: "",
    UnAccountedNetQuantity: "",
    UnAccountedGrossQuantity: "",
    GrossStartTotalizer: "",
    GrossEndTotalizer: "",
    NetStartTotalizer: "",
    NetEndTotalizer: "",
    BaseProductCode: "",
    TransportationType: "",
    ShareholderCode: "",
    ReconciliationCode: "",
    UnAccountedTransactionTypeCode: "",
    Attributes: [],
};

export const emptyTerminal = {
    Active: true,
    Address: "",
    City: "",
    Code: "",
    ContactPerson: "",
    Country: "",
    Email: null,
    EnterpriseProcesses: [],
    IsRedundant: false,
    Latitude: "",
    Longitude: "",
    Name: "",
    Phone: "",
    State: "",
    TimeZone: 0,
    ZipCode: "",
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    Remarks: "",
    DCHAttributes: [],
    Attributes: [],
};

export const emptyTankGroup = {
    Code: "",
    Name: "",
    Description: "",
    BaseProductCode: "",
    ActiveTankCode: "",
    Active: false,
    Remarks: "",
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    TerminalCode: "",
    TankCollection: [],
    MeterCollection: [],
};

export const emptyMeter = {
    Code: "",
    Name: "",
    Attributes: [],
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    Remarks: "",
    Description: "",
    Active: true,
    MeterCodeList: [],
    MeterType: "",
    TankGroupCode: null,
    MeterLineType: "",
    ProductDensityInput: "",
    MeterNumber: "",
    ConjunctionNumber: "",
    BaseproductList: [],
    Virtual: false,
    TankGroupList: [],
    MeterBaseUOM: null
};

export const emptyTank = {
    Code: "",
    Name: "",
    Description: "",
    TankGroupCode: "",
    TankMode: "",
    TerminalCode: "",
    Active: false,
    Remark: "",
    BaseProductCode: "",
    Capacity: "",
    CapacityUOM: "",
    Density: "",
    DensityUOM: "",
    Temperature: "",
    TemperatureUOM: "",
    TankLevel: "",
    GrossVolume: "",
    GrossVolumeUOM: "",
    NetVolume: "",
    NetVolumeUOM: "",
    WaterLevel: "",
    WaterVolume: "",
    AvailableRoom: "",
    Attributes: [],
    TankNetMassUOM: "",
    LastActive: new Date(),
    CreatedTime: new Date(),
    UpdatedTime: new Date(),
    AtgLastUpdatedTime: new Date(),
    TankDensity2: 0,
    TankDensity2UOM: "",
    IsBonded: false,
    Pressure: "",
    PressureUOM: "",
    VapourGrossQuantity: "",
    VapourNetQuantity: "",
    VapourUOM: "",
    LevelUOM: "",
    TankNetMass: 0,
    GrossMassUOM: "",
    GrossMass: "",
    WaterVolumeUOM: "",
    BPDensityUOM: "",
    BPMinDensity: "",
    BPMaxDensity: "",
};

export const emptyRailMarineTransactionProductInfo = {
    LeakageTotalizer: "",
    TransactionID: "",
    FlangeNumber: "",
    KFactorCurrent: "",
    KFactorProved: "",
    VapourGrossQuantity: "",
    VapourNetQuantity: "",
    VapourUOM: "",
    MeterCode: "",
    TankCode: "",
    PresetQuantity: "",
    NetEndTotalizer: "",
    CalculatedValue: "",
    ResetQuantity: "",
    WeightInAir: "",
    WeightInAirUOM: "",
    WeightInVaccum: "",
    WeightInVaccumUOM: "",
    Remarks: "",
    GrossMass: "",
    MassUOM: "",
    Attributes: [],
    CalculatedGross: "",
    CalculatedNet: "",
    UnitPrice: "",
    CalculatedValueUOM: "",
    NetStartTotalizer: "",
    StartTotalizer: "",
    TankStartSnapShot: null,
    TankEndSnapShot: null,
    ShareHolderCode: "",
    FinishedProductCode: "",
    BaseProductCode: "",
    AdditiveProductCode: "",
    ArmCode: "",
    IsInOffSpec: null,
    InjectorPosition: "",
    GrossQuantity: "",
    NetQuantity: "",
    EndTotalizer: "",
    QuantityUOM: "",
    TemperatureUOM: "",
    Pressure: "",
    PressureUOM: "",
    FlowRate: "",
    FlowRateUOM: "",
    VCF: "",
    ProductDensity: "",
    ProductDensityUOM: "",
    ReferenceDensity: "",
    StartTime: "",
    EndTime: "",
    Temperature: "",
    BatchID: "",
};

export const emptyMarineRailTransactionCommonInfo = {
    CompartmentSeqNoInVehicle: "",
    BayCode: "",
    BCUCode: "",
    UnLoadingArm: "",
    StartTime: "",
    EndTime: "",
    FinishedProductCode: "",
    QuantityUOM: "",
    Remarks: "",
    TransactionID: "",
    GrossQuantity: "",
    NetQuantity: "",
    Temperature: "",
    TemperatureUOM: "",
    ProductDensity: "",
    ProductDensityUOM: "",
    ReferenceDensity: "",
    MeterCode: "",
    StartTotalizer: "",
    EndTotalizer: "",
    NetStartTotalizer: "",
    NetEndTotalizer: "",
    GrossMass: "",
    MassUOM: "",
    Pressure: "",
    PressureUOM: "",
    CalculatedGross: "",
    CalculatedNet: "",
    CalculatedValueUOM: "bbl",
    Attributes: [],
};

export const emptyReceiptCompartmentPlan = {
    ReceiptCode: "",
    TrailerCode: "",
    CarrierCompanyCode: "",
    CompartmentCode: "",
    SequenceNo: "",
    ShareholderCode: "",
    FinishedProductCode: "",
    ReceiptCompartmentStatus: "",
    PlannedQuantity: "",
    AdjustedPlanQuantity: "",
    PlanQuantityUOM: "",
    NetLoadedQuantity: "",
    UnloadedQuantity: "",
    CompartmentSeqNoInVehicle: null,
    UnloadedQuantityUOM: "",
    PurgingRequired: false,
    PurgingCompleted: false,
    HSEInspectionStatus: null,
    Attributes: [],
    AssociatedOrderItems: [],
    AssociatedContractItems: [],
    ReceiptCompartmentTanks: [],
    IsTransloading: false,
};
export const emptyReceiptCompartmentTanks = {
    TrailerCode: "",
    CompartmentCode: "",
    CompartmentSeqNoInVehicle: "",
    TankCode: "",
    PlannedQuantity: "",
    PlanQuantityUOM: "",
    UnLoadedQuantity: "",
};

export const emptyAccessCard = {
    PIN: "",
    LogicalPIN: null,
    Password: null,
    ConfirmPassword: null,
    Description: null,
    CardType: null,
    passwordExpiryDate: null,
    IssueDate: null,
    ExpiryDate: null,
    CardStatus: null,
    PointName: null,
    PasswordFailureCount: 0,
    PasswordFailureTime: null,
    Locked: false,
    LastLockingTime: null,
    ActivationTime: null,
    MarkedForDeletion: false,
    Active: true,
    Remarks: null,
    LastActiveTime: null,
    CreatedTime: new Date(),
    LastUpdatedTime: null,
    LastUpdatedBy: null,
    ShareholderCode: "",
    IsAssoiciate: false,
    EntityName: null,
    EntityValue: null,
    CarrierCode: null,
    FASCN: null,
    ISTWICCARD: false,
    Attributes: [],
};

export const emptyRailMarineTransactionCommonInfo = {
    ReceiptCode: "",
    LoadingType: "",
    BayCode: "",
    BCUCode: "",
    CompartmentSeqNoInVehicle: "",
    CompartmentSeqNoInTrailer: "",
    CompartmentCode: "",
    IsBonded: false,
    TrailerCode: "",
    CarrierCode: "",
    GeneralTMUserCode: "",
    TransactionType: "",
    DispatchCode: "",
    OfficerName: "",
    GeneralTMUserName: "",
    TransportationType: "",
    VehicleCode: "",
    IsInvalid: false,
};

export const emptySealMaster = {
    Code: "",
    CurrentSealNo: "",
    StartSealNo: "",
    EndSealNo: "",
    Prefix: "",
    Suffix: "",
    CreatedTime: new Date(),
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    Attributes: [],
};

export const emptyRailMarineFinishedProductInfoInfo = {
    CompartmentSeqNoInVehicle: "",
    BayCode: "",
    BCUCode: "",
    LoadingArm: "",
    QuantityUOM: "",
    StartTime: new Date(),
    EndTime: new Date(),
    TransactionID: "",
    Remarks: "",
    GrossQuantity: "",
    NetQuantity: "",
    Temperature: "",
    TemperatureUOM: "",
    ProductDensity: "",
    ProductDensityUOM: "",
    StartTotalizer: "",
    EndTotalizer: "",
    NetStartTotalizer: "",
    NetEndTotalizer: "",
    MeterCode: "",
    GrossMass: "",
    MassUOM: "",
    Pressure: "",
    PressureUOM: "",
    CalculatedGross: "",
    CalculatedNet: "",
    CalculatedValueUOM: "bbl",
    ReferenceDensity: "",
    FinishedProductCode: "",
    TankCode: "",
    TankStartGrossQuantity: "",
    TankEndGrossQuantity: "",
    TankStartNetQuantity: "",
    TankEndNetQuantity: "",
    TankStartMass: "",
    TankEndMass: "",
    TankStartPressure: "",
    TankEndPressure: "",
};

export const emptyMarineDispatchTransactionCommonInfo = {
    CompartmentSeqNoInVehicle: "",
    BayCode: "",
    BCUCode: "",
    LoadingArm: "",
    StartTime: new Date(),
    EndTime: new Date(),
    FinishedProductCode: "",
    QuantityUOM: "",
    Remarks: "",
    TransactionID: "",
    GrossQuantity: "",
    NetQuantity: "",
    Temperature: "",
    TemperatureUOM: "",
    ProductDensity: "",
    ProductDensityUOM: "",
    ReferenceDensity: "",
    MeterCode: "",
    StartTotalizer: "",
    EndTotalizer: "",
    NetStartTotalizer: "",
    NetEndTotalizer: "",
    GrossMass: "",
    MassUOM: "",
    Pressure: "",
    PressureUOM: "",
    CalculatedGross: "",
    CalculatedNet: "",
    CalculatedValueUOM: "bbl",
    Attributes: [],
};

export const emptyRailMarineTransactionBPInfo = {
    GrossQuantity: "",
    NetQuantity: "",
    Temperature: "",
    TemperatureUOM: "",
    ProductDensity: "",
    ProductDensityUOM: "",
    ReferenceDensity: "",
    MeterCode: "",
    StartTotalizer: "",
    EndTotalizer: "",
    NetStartTotalizer: "",
    NetEndTotalizer: "",
    GrossMass: "",
    MassUOM: "",
    Pressure: "",
    PressureUOM: "",
    CalculatedGross: "",
    CalculatedNet: "",
    CalculatedValueUOM: "bbl",
    TankCode: "",
    TankStartGrossQuantity: "",
    TankEndGrossQuantity: "",
    TankStartNetQuantity: "",
    TankEndNetQuantity: "",
    TankStartGrossMass: "",
    TankEndGrossMass: "",
    TankStartPressure: "",
    TankEndPressure: "",
    Attributes: [],
};

export const emptyArrTransactionBP = {
    BaseProductCode: "",
    TankCode: "",
    TankStartSnapShot: {
        MassUOM: "",
        GrossVolume: "",
        NetVolume: "",
        GrossMass: "",
        Pressure: "",
    },
    TankEndSnapShot: {
        MassUOM: "",
        GrossVolume: "",
        NetVolume: "",
        GrossMass: "",
        Pressure: "",
    },
};

export const ArrTransactionAdditive = {
    BaseProductCode: "",
    AdditiveCode: "",
    TankStartSnapShot: {
        MassUOM: "",
        GrossVolume: "",
        NetVolume: "",
        GrossMass: "",
        Pressure: "",
    },
    TankEndSnapShot: {
        MassUOM: "",
        GrossVolume: "",
        NetVolume: "",
        GrossMass: "",
        Pressure: "",
    },
};

export const emptyDispatchCompartmentPlan = {
    DispatchCode: "",
    TrailerCode: "",
    CarrierCompanyCode: "",
    CompartmentCode: "",
    SequenceNo: "",
    ShareholderCode: "",
    FinishedProductCode: "",
    PlannedQuantity: "",
    AdjustedPlanQuantity: "",
    PlanQuantityUOM: "",
    NetLoadedQuantity: "",
    ReturnQuantity: "",
    LoadedQuantity: "",
    CompartmentSeqNoInVehicle: null,
    LoadedQuantityUOM: "",
    BlendState: null,
    PurgingRequired: false,
    PurgingCompleted: false,
    HSEInspectionStatus: null,
    Attributes: [],
    AssociatedOrderItems: [],
    AssociatedContractItems: [],
    DispatchCompartmentTanks: [],
};

export const emptyDispatchCompartmentTanks = {
    TrailerCode: "",
    CompartmentCode: "",
    CompartmentSeqNoInVehicle: "",
    TankCode: "",
    PlannedQuantity: "",
    PlanQuantityUOM: "",
    LoadedQuantity: "",
    AdjustedPlanQuantity: "",
};

export const emptySlotConfiguration = {
    TerminalCode: "",
    TransportationType: "",
    SlotParams: getSlotParameters(mapSlotParameterValidationDef),
};
export const emptySlotConfigurationForAPI = {
    TerminalCode: "",
    TransportationType: "",
    SlotParams: [],
};
export const emptySlotParam = {
    Name: "",
    Value: "",
    DefaultValue: "",
    Description: "",
    DataType: "",
};
export const emptyWeekendHolidays = {
    Sunday: false,
    Monday: false,
    Tuesday: false,
    Wednesday: false,
    Thursday: false,
    Friday: false,
    Saturday: false,
};

export const emptyEodAdminInfo = {
    ArchivalStatus: "",
    CloseTime: "",
    ContinueIfBayNotLoadedFlag: "",
    CurrentAction: "",
    DenyEntryTime: "",
    DenyLoadTime: "",
    DenyOpen: "",
    ID: "00000000-0000-0000-0000-000000000000",
    IsCloseAutomatic: "",
    IsOpenAutomatic: "",
    OpenTime: "",
    PurgeStatus: "",
    Remarks: "",
    Status: "",
    IfBayNotLoadedContinue: "",
    Action: "",
    ActionID: "",
    Description: "",
};
export const emptyTruckManualEntryLoadingDetailsCommonInfo = {
    ShipmentCode: "",
    DriverCode: "",
    CarrierCode: "",
    VehicleCode: "",
    TrailerCode: "",
    CompartmentCode: "",
    CompartmentSeqNoInTrailer: "",
    CompartmentSeqNoInVehicle: "",
    BCUCode: "",
    BayCode: "",
    ShareHolderCode: "",
    LoadingDetailsType: "",
    ReceiptCode: "",
};

export const emptyTruckManualEntryLoadingProductInfo = {
    TransactionID: "",
    FlangeNumber: "",
    KFactorCurrent: "",
    KFactorProved: "",
    VapourGrossQuantity: "",
    VapourNetQuantity: "",
    VapourUOM: "",
    MeterCode: "",
    TankCode: "",
    PresetQuantity: "",
    CalculatedValue: "",
    UnitPrice: "",
    ResetQuantity: "",
    WeightInAir: "",
    WeightInAirUOM: "",
    WeightInVaccum: "",
    WeightInVaccumUOM: "",
    Remarks: "",
    Attributes: [],
    CalculatedGross: "",
    CalculatedNet: "",
    LeakageTotalizer: "",
    CalculatedValueUOM: "",
    NetEndTotalizer: "",
    EndTotalizer: "",
    FinishedProductCode: "",
    BaseProductCode: "",
    AdditiveProductCode: null,
    LoadingArmCode: "",
    IsInOffSpec: "",
    InjectorPosition: "",
    GrossQuantity: "",
    NetQuantity: "",
    QuantityUOM: "",
    Temperature: "",
    TemperatureUOM: "",
    Pressure: "",
    PressureUOM: "",
    FlowRate: "",
    FlowRateUOM: "",
    VCF: "",
    ProductDensity: "",
    ProductDensityUOM: "",
    StartTime: new Date(),
    EndTime: new Date(),
    StartTotalizer: "",
    NetStartTotalizer: "",
    BatchID: "",
};

export const emptyMarineOperatorDashboardFilterInfo = {
    selectList: [],
    timeTaken: 1,
    graphDuration: 12,
    transactionStatus: "",
};

export const emptyOthersOperatorDashboardFilterInfo = {
    selectList: [],
    timeTaken: 1,
    graphDuration: 4,
    transactionStatus: "",
};

export const emptyDeviceInfo = {
    Attributes: [],
    IsIntegrated: false,
    LastUpdatedBy: "",
    MultiDrop: false,
    LastUpdated: new Date(),
    Created: new Date(),
    LastActive: new Date(),
    Remarks: "",
    Active: true,
    PointName: "",
    Model: "",
    NodeAddress: "",
    Description: "",
    Name: "",
    Code: "",
    TerminalCode: "",
    AssociatedChannels: [],
    DeviceType: ""
}

export const emptyBCUDeviceInfo = {
    Code: "",
    Name: "",
    Active: true,
    Remarks: "",
    DeviceType: 0,
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    AdditiveUOM: "mL",
    DensityUOM: "kg/m3",
    Description: "",
    LastUpdatedBy: "",
    Attributes: [],
    AssociatedChannels: [],
    ESDTagName: "",
    IsDualBay: false,
    IsTransloading: false,
    MassUOM: "kg",
    Model: "",
    MultiDrop: false,
    NoOfAdditive: 0,
    NoOfArms: 0,
    NodeAddress: "",
    PointName: "",
    PressureUOM: "kPa",
    Prover: false,
    ReceiptSource: null,
    TemperatureUOM: "degC",
    TerminalCode: "",
    RecipeConfiguration: null,
    VPConfiguration: null,
    DIDOList: [],
    PermissiveConfigList: {},
    CardReaderCode: "",
    Status: null,
    LastActive: new Date(),
}
export const emptyCardReaderDeviceInfo = {
    Attributes: [],
    IsIntegrated: false,
    LastUpdatedBy: "",
    MultiDrop: false,
    LastUpdated: new Date(),
    Created: new Date(),
    LastActive: new Date(),
    Remarks: "",
    Active: true,
    PointName: "",
    Model: "",
    NodeAddress: "",
    Description: "",
    Name: "",
    Code: "",
    TerminalCode: "",
    AssociatedChannels: [],
    DeviceType: 2
}
export const emptyWBDeviceInfo = {
    Weight: null,
    LastUpdatedBy: "",
    MultiDrop: false,
    LastUpdatedTime: new Date(),
    CreatedTime: new Date(),
    LastActive: new Date(),
    Remarks: "",
    Active: true,
    WeightUOM: "",
    TerminalCode: "",
    IsAuto: true,
    PointName: "",
    NodeAddress: "",
    Model: "",
    Description: "",
    Name: "",
    Code: "",
    Attributes: [],
    DeviceType: 3
}
export const emptyDEUDeviceInfo = {
    PointName: "",
    AttributeList: [],
    LastUpdatedBy: "",
    MultiDrop: false,
    CreatedTime: new Date(),
    LastActiveTime: new Date(),
    LastUpdatedTime: new Date(),
    Remarks: "",
    Active: true,
    AssociatedChannels: [],
    ESDTagName: "",
    ResponseWaitTime: 0,
    RefreshTime: 0,
    NodeAddress: "",
    DEUType: "",
    Description: "",
    Name: "",
    Code: "",
    TerminalCode: "",
    DeviceType: 1
}

export const emptyCaptain = {
    Active: true,
    UserType: "",
    Code: "",
    Name: "",
    Address: null,
    Status: true,
    Attributes: [],
    Remarks: "",
    Phone: "",
    Mobile: "",
    MailID: "",
    LastActiveDate: new Date(),
    CreatedDate: new Date(),
    LastUpdatedDate: new Date(),
    LastUpdatedBy: null,
    ShareholderCodes: [],
    TerminalCodes: [],
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    TransportationTypes: [],
    AssociatedSuppliers: [],
    LastActive: new Date(),
    LastReportTime: new Date(),
    GeneralTMUserImage: []
}
export const emptyBayGroup = {
    GroupName: "",
    Description: "",
    BayList: [],
    LastUpdatedBy: null,
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
}

export const emptyWebPortalUser = {
    UserName: "",
    RoleName: "",
    UserPrincipal: "",
    WebPortalUserEntityItems: [],
};

export const emptyPipelineHeader = {
    Code: "",
    Name: "",
    Description: "",
    PipelineHeaderType: "",
    PointName: "",
    OuterDiameter: "",
    OuterDiameterUOM: null,
    WallThickness: "",
    WallThicknessUOM: null,
    TypicalFlowRatePerHour: "",
    FlowRateUOM: null,
    Active: true,
    AssociatedMeterCodes: [],
    Attributes: [],
    CreatedTime: new Date(),
    LastActive: new Date(),
    LastUpdatedTime: new Date(),

};
export const emptyExchangePartner = {
    ExchangePartnerName: "",
    SellerCode: "",
    FinalShipperCode: "",
    IsActive: true,
    SellerId: "",
    FinalShipperID: "",
    AgreementEndTime: new Date(),
    AgreementStartTime: new Date()

}

export const emptyUser = {
  PersonID: "",
  IsServiceUser: "",
  FirstName: "",
  LastName: "",
  Department: "",
  Email: "",
  FullName: "",
  Culture: "",
  ShareHolderID: "",
  Remarks: "",
  LastActive: new Date(),
  Status: true,
  Phone: "",
  Mobile: "",
  UserName: "",
  LastUpdated: new Date(),
  CreationTime: new Date(),
  Description: "",
  DomainName: "",
  UserAccount: "",
  GroupName: "",
  RoleName: "",
  Validate: false,
  PrimaryShareholder: "",
  SecondaryShareholders: [],
  ApplicationID: ""
}




export const emptyPipelineSnapshotInfo = {
    TransactionType: "",
    PlanCode: "",
    ShareholderCode: "",
    GrossQuantity: "",
    NetQuantity: "",
    QuantityUOM: "",
    RationPending: false,
    Remarks: "",
    LastUpdatedBy: "",
    ApprovedBy: "",
    PipelineTransactionID: "",
    IsInvalid: false
}

export const emptyPipelineCommonTransactionSnapshotInfo = {
    Pressure: "",
    PressureUOM: "",
    WeightInAir: "",
    WeightInAirUOM: "",
    WeightInVacuum: "",
    WeightInVacuumUOM: "",
    VapourGrossQuantity: "",
    VapourNetQuantity: "",
    FlowRateUOM: "",
    VapourUOM: "",
    TankLevel: "",
    TankMode: "",
    WaterLevel: "",
    WaterVolume: "",
    IsManualEntry: false,
    IsStart: false,
    IsEnd: false,
    IsInvalid: false,
    VCF: "",
    FlowRate: "",
    KFactorCurrent: "",
    KFactorProved: "",
    TransactionType: "",
    PipelineHeaderCode: "",
    State: "",
    MeterCode: "",
    TankCode: "",
    IsTankBonded: false,
    ScanStartTime: new Date(),
    ScanEndTime: new Date(),
    NetVolume: "",
    GrossVolume: "",
    NetStartVolume: "",
    GrossStartVolume: "",
    NetEndVolume: "",
    GrossEndVolume: "",
    GrossMass: "",
    Temperature: "",
    Density: "",
    ReferenceDensity: "",
    VolumeUOM: "",
    MassUOM: "",
    TemperatureUOM: "",
    DensityUOM: "",
    GrossTotalizer: "",
    GrossStartTotalizer: "",
    GrossEndTotalizer: "",
    NetTotalizer: "",
    NetStartTotalizer: "",
    NetEndTotalizer: "",
    LastUpdatedBy: "",
    Attributes: ""
}


export const emptyProcessConfigInfo = {
    ProcessName: "",
    WorkFlowType: "",
    PrimaryDeviceType: "",
    PrimaryDeviceCode: "",
    Active: true,
    Remarks: "",
    AssociatedDevices: [],
    LastActiveTime: new Date(),
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    Attributes: []
}



export const emptyReconciliationInfo = {
    ReconciliationCode: "",
    EntityTypeCode: "",
    StartDate: new Date(),
    EndDate: new Date(),
    Status: true,
    Remarks: "",
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    LastUpdatedBy: null,
    ReconciliationMeterDetails: [],
    ReconciliationTankDetails: [],
    UnAccountedTransactionMeterDetails: [],
    UnAccountedTransactionTankDetails: [],
    RefreshWithLatestTransactions: true,
    ReportWarnings: "",
};

export const emptyReconciliationScheduleInfo = {
    EntityTypeCode: "",
    ScheduleName: "",
    IsEOS: false,
    IsEOD: false,
    StartDateTime: null,
    EndDateTime: null,
    IsRecurrent: "",
    Active: false,
    LastActiveTime: null,
    LastUpdatedTime: null,
    LastUpdatedBy: null
};
export const emptyATGTank = {
    TankCode: "",
    TankName: "",
    EnableTankScan: false,
    AtgAttributeConfigurationData: [{
        Parameter: {
            Point: "",
            Parameter: ""
        }
    }]
}
export const emptyLookUpData = {
    readonly: false,
    value: ""
}

export const emptyProductAllocation = {
    EntityCode: "",
    EntityType: "",
    ShareholderCode: "",
    Description: null,
    Source: "",
    CreatedTime: new Date(),
    LastUpdatedTime: new Date(),
    LastUpdatedBy: null,
    ProductAllocationEntityItems: []
}
export const emptyMasterConfigurationInfo = {
    AttributeName: "",
    ParameterName: ""
}
export const emptyScadaBayList = {
  Code: "",
  PointName: ""
}
export const emptyNotificationGroup = {
  GroupCode: "",
  Active: true,
  Description: ""
}
export const emptyNotificationRestriction = {
  MessageCode: "",
  MessageSource: ""
}
export const emptyWeighBridge = {
    Weight: "",
    IsAuto: false
}
export const emptyNotificationMessage = {
  Active: true,
  Condition: "",
  GroupCode: "",
  Message: "",
  MessageCode: "",
  MessageType: "",
  NotificationLocation: "",
  NotificationType: "",
  PointName: "",
  Priority: "",
  ReturnToNormal: true

}

export const emptyATGMaster = {
  AtgScanPeriod: "",
  AtgMasterConfigurations: [{
    ATGValueDataType: "",
    AttributeDataType: "",
    Description: "",
    EnableScan: true,
    IsExtendedAttribute: false,
    ParameterName: "",
    ShowInReports: true,
    TankAttributeCode: "",
    TankAttributeName: "",
    UOM: "",
    UOMAttributeCode: "",
    UOMType: ""
  }],
}
export const emptyReportSchedule = {
    ReportName: "",
    ScheduleName: "",
    ParamData: "",
    IsEOD: false,
    IsEOS: false,
    IsSave: false,
    IsPrint: false,
    IsDaily: false,
    IsWeekly: false,
    IsMonthly: false,
    Printer: "",
    ShareholderCode: ""
}

export const emptyRole = {
  RoleName: "",
  Description: "",
  CreatedTime: new Date(),
  LastUpdatedTime: new Date(),
  MenuItems: [],
  FunctionGroupItems: []
}
export const emptyShareHolderAgreement = {
  ExchangeAgreementItems: [],
  Attributes: [],
  ExchangeAgreementCreatedBy: null,
  ExchangeAgreementCreatedDate: new Date(),
  LastUpdatedTime: new Date(),
  LastUpdatedBy: null,
  CreatedTime: new Date(),
  LastActiveTime: new Date(),
  StartDate: null,
  EndDate: null,
  ProductTransferAgreement: {},
  IsBonded: false,
  RequestStatus: "",
  RequestorShareholderCode: "",
  LenderShareholderCode: "",
  RequestType: "",
  RequestCode: "",
  Remarks: "",
  TerminalCode: ""
}
export const emptyCustomerStockTransfer = {
  Code: "",
  RequestorShareholderCode: "",
  RequestorCustomerCode: "",
  LenderShareholderCode: "",
  LenderCustomerCode: "",
  CustomerAgreementItems: [],
  TransferDate: new Date()
}

export const emptyShiftConfig = {
  ID: "",
  Name: "",
  StartTime: new Date(),
  EndTime: new Date(),
  Remarks: "",
  TerminalCode: ""
}
export const emptyInitialConfig = {
  CustomerCode: "",
  ShareholderCode: "",
  BaseProductCode: "",
  QuantityUOM: "",
  GrossAvailableQuantity: ""
}
export const emptyCustomerRecipe = {
  Code: "",
  ShareholderCode: "",
  FinishedProduct: emptyFinishedProduct,
  CustomerCodes: [],
  TerminalCode: "",
  LastActiveTime: new Date(),
  CreatedTime: new Date(),
  LastUpdatedTime: new Date(),
  LastUpdatedBy: null,
  Status: true,
  Remarks: ""
}

export const emptyCOAParameter = {
  Name: "",
  Specification: "",
  Method: "",
  Description: "",
  IsActive: true,
  Remarks: "",
  LastUpdatedTime: new Date(),
  LastUpdatedBy: null
};
export const emptyCOATemplate = {
  COATemplateCode: "",
  TankCode:null,
  BaseProductCode:"",
  UseType:null,
  FromTemplate:null,
  IsActive:true,
  Remarks:"",
  LastUpdatedBy:"",
  LastUpdatedTime:new Date(),
  CreatedBy:"",
  CreatedTime:new Date(),
  Attributes: []
};
export const emptyCOAManagement = {
  COACode:"",
  COAType:"",
  TankCode:null,
  TemplateCode:null,
  BaseProductCode:"",
  BaseProductName:"",
  LOTNumber:"",
  LastUpdatedTime:new Date(),
  CreatedBy:"",
  LastUpdatedBy:"",
  Remarks:"",
  TransactionCode:"",
  FinishedProductCode:"",
  BaseProductID:null,
  Attributes: []
};
export const emptyCOAManagementFinishedProduct = {
  COACode:"",
  COAType:"",
  TankCode:null,
  LOTNumber:"",
  LastUpdatedTime:new Date(),
  CreatedBy:"",
  LastUpdatedBy:"",
  Remarks:"",
  TransactionCode:"",
  FinishedProductCode:"",
  Attributes: []
};
export const emptyCOACustomer = {
  CustomerCode:"",
  FinishedProductCode:"",
  BaseProductCode:"",
  TemplateCode:"",
  CreatedBy:"",
  LastUpdatedBy:"",
  Attributes: []
};
export const emptyCOAAssignment = {
    ShareholderCode: "",
    TransactionCode: "",
    TransactionStatus: "",
    TransportationType: "",
    TransactionType: "",
    COATransactionCompartments: [],
    Attributes: [],
};

export const COATransactionCompartments = {
    TransportationType: "",
    CompartmentSeqNumber: -1,
    CustomerCode: "",
    DestinationCode: "",
    FinishedProductCode: "",
    CreatedBy: "",
    CreatedTime: new Date(),
    LastUpdatedBy: "",
    LastUpdatedTime: new Date(),
    COATransactionCompartmentDetails: [],
}

export const COATransactionCompartmentDetailInfo = {
    ID: "",
    BayCode: "",
    TankCode: "",
    BaseCOACode: "",
    FinishedProductCOACode: "",
    CreatedBy: "",
    CreatedTime: new Date(),
    BaseCOANumber: "",
    FinishedProductCOANumber: "",
    CoaTransactionCompartmentDetailParameterInfos: [],
}

export const CoaTransactionCompartmentDetailParameterInfos = {
    TransactionCompartmentDetailId: "",
    Name: "",
    Specification: "",
    Method: "",
    Result: "",
    Sortindex: 0,
    Remarks: "",
}

export const emptyCOATankManagement = {
    COACode: "",
    COAType: "",
    TankCode: "",
    TemplateCode: "",
    BaseProductCode: "",
    BaseProductName: "",
    LOTNumber: "",
    LastUpdatedTime: new Date(),
    CreatedBy: "",
    LastUpdatedBy: "",
    Remarks: "",
    TransactionCode: "",
    FinishedProductCode: "",
    BaseProductID: "",
    Attributes: [],
    ShareholderCode: ""
};
